### ISSUE TITLE
System.system.read_data is unable to read conformations from .nc file generated by MDAnalysis

### ISSUE THREAD

**Issue by CornyC** [JMorado/ParaMol#82]
Reading smallbox.nc file for system mp0.
smallbox.nc does not contain coordinates data.
smallbox.nc does not contain forces data.
smallbox.nc does not contain reference energies data.
Data of system mp0 was read from file smallbox.nc
[smallbox.zip](https://github.com/JMorado/ParaMol/files/9970865/smallbox.zip)

**Comment by JMorado** [comment]
ParaMol's .nc files do not have the same variables as MDAnalysis files, so this is expected.

https://paramol.readthedocs.io/en/latest/Files_specification.html#netcdf-file-specification

Assuming you are using external data, you must first read it into your script using external libraries or your own code, and then set the system.ref_energies, system.ref_coordinates, and system.ref_forces (if required) attributes. Once system has this info, you can read/write ParaMol's .nc files using the system's methods read_data/write_data. See for more details:

https://paramol.readthedocs.io/en/latest/ParaMol_Package/ParaMol.System.system.html
